//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Orwell.TSP {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResourceException {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceException() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Orwell.TSP.ResourceException", typeof(ResourceException).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The attribute Nome Messaggio is wrong in the element Testata.
        /// </summary>
        internal static string NomeMessaggioTestata {
            get {
                return ResourceManager.GetString("NomeMessaggioTestata", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to The element Testata is missing.
        /// </summary>
        internal static string Testata
        {
            get
            {
                return ResourceManager.GetString("Testata", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The attribute TimestampTestata is missing in the element Testata.
        /// </summary>
        internal static string TimestampTestata
        {
            get
            {
                return ResourceManager.GetString("TimestampTestata", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The attribute CanaleTestata is missing in the element Testata.
        /// </summary>
        internal static string CanaleTestata
        {
            get
            {
                return ResourceManager.GetString("CanaleTestata", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The attribute KeyTestata is missing in the element Testata.
        /// </summary>
        internal static string KeyTestata
        {
            get
            {
                return ResourceManager.GetString("KeyTestata", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The element BollettinoPremarcato is missing.
        /// </summary>
        internal static string BollettinoPremarcato
        {
            get
            {
                return ResourceManager.GetString("BollettinoPremarcato", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The attribute IdUtenza is missing in the element BollettinoPremarcato.
        /// </summary>
        internal static string IdUtenzaBollettinoPremarcato
        {
            get
            {
                return ResourceManager.GetString("IdUtenzaBollettinoPremarcato", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The attribute CodiceSIAAzienda is missing in the element BollettinoPremarcato.
        /// </summary>
        internal static string CodiceSIAAziendaBollettinoPremarcato
        {
            get
            {
                return ResourceManager.GetString("CodiceSIAAziendaBollettinoPremarcato", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The attribute TipoDocumento is missing in the element BollettinoPremarcato.
        /// </summary>
        internal static string TipoDocumentoBollettinoPremarcato
        {
            get
            {
                return ResourceManager.GetString("TipoDocumentoBollettinoPremarcato", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The attribute TipoDocumento is missing in the element BollettinoPremarcato.
        /// </summary>
        internal static string NumBollettinoBollettinoPremarcato
        {
            get
            {
                return ResourceManager.GetString("NumBollettinoBollettinoPremarcato", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The attribute ImportoBollettino is missing in the element BollettinoPremarcato.
        /// </summary>
        internal static string ImportoBollettinoBollettinoPremarcato
        {
            get
            {
                return ResourceManager.GetString("ImportoBollettinoBollettinoPremarcato", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The element Verifica is missing.
        /// </summary>
        internal static string Verifica
        {
            get
            {
                return ResourceManager.GetString("Verifica", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The attribute AbiMittente is missing in the element Verifica.
        /// </summary>
        internal static string AbiMittenteVerifica
        {
            get
            {
                return ResourceManager.GetString("AbiMittenteVerifica", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The attribute ImportoBollettino is missing in the element Verifica.
        /// </summary>
        internal static string AbiOrdinanteVerifica
        {
            get
            {
                return ResourceManager.GetString("AbiOrdinanteVerifica", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The element BollettinoBianco is missing.
        /// </summary>
        internal static string BollettinoBianco
        {
            get
            {
                return ResourceManager.GetString("BollettinoBianco", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The attribute IdUtenza is missing in the element BollettinoBianco.
        /// </summary>
        internal static string IdUtenzaBollettinoBianco
        {
            get
            {
                return ResourceManager.GetString("IdUtenzaBollettinoBianco", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The attribute CodiceSIAAzienda is missing in the element BollettinoBianco.
        /// </summary>
        internal static string CodiceSIAAziendaBollettinoBianco
        {
            get
            {
                return ResourceManager.GetString("CodiceSIAAziendaBollettinoBianco", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The attribute TipoDocumento is missing in the element BollettinoBianco.
        /// </summary>
        internal static string TipoDocumentoBollettinoBianco
        {
            get
            {
                return ResourceManager.GetString("TipoDocumentoBollettinoBianco", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The attribute ImportoBollettino is missing in the element BollettinoBianco.
        /// </summary>
        internal static string ImportoBollettinoBollettinoBianco
        {
            get
            {
                return ResourceManager.GetString("ImportoBollettinoBollettinoBianco", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The element DatiBeneficiario is missing.
        /// </summary>
        internal static string DatiBeneficiario
        {
            get
            {
                return ResourceManager.GetString("DatiBeneficiario", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The attribute DatiAnagrafici is missing in the element DatiBeneficiario.
        /// </summary>
        internal static string DatiAnagraficiDatiBeneficiario
        {
            get
            {
                return ResourceManager.GetString("DatiAnagraficiDatiBeneficiario", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The attribute CausaleVersamento is missing in the element DatiBeneficiario.
        /// </summary>
        internal static string CausaleVersamentoDatiBeneficiario
        {
            get
            {
                return ResourceManager.GetString("CausaleVersamentoDatiBeneficiario", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The element DatiCliente is missing.
        /// </summary>
        internal static string DatiCliente
        {
            get
            {
                return ResourceManager.GetString("DatiCliente", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The attribute Nominativo is missing in the element DatiCliente.
        /// </summary>
        internal static string NominativoDatiCliente
        {
            get
            {
                return ResourceManager.GetString("NominativoDatiCliente", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The attribute Indirizzo is missing in the element DatiCliente.
        /// </summary>
        internal static string IndirizzoDatiCliente
        {
            get
            {
                return ResourceManager.GetString("IndirizzoDatiCliente", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The attribute CAP is missing in the element DatiCliente.
        /// </summary>
        internal static string CAPDatiCliente
        {
            get
            {
                return ResourceManager.GetString("CAPDatiCliente", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The attribute Citta is missing in the element DatiCliente.
        /// </summary>
        internal static string CittaDatiCliente
        {
            get
            {
                return ResourceManager.GetString("CittaDatiCliente", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The attribute Provincia is missing in the element DatiCliente.
        /// </summary>
        internal static string ProvinciaDatiCliente
        {
            get
            {
                return ResourceManager.GetString("ProvinciaDatiCliente", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The element Addebito is missing.
        /// </summary>
        internal static string Addebito
        {
            get
            {
                return ResourceManager.GetString("Addebito", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to The attribute TipoStrumento is missing in the element Addebito.
        /// </summary>
        internal static string TipoStrumentoAddebito
        {
            get
            {
                return ResourceManager.GetString("TipoStrumentoAddebito", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The element Conferma is missing.
        /// </summary>
        internal static string Conferma
        {
            get
            {
                return ResourceManager.GetString("Conferma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The attribute IdTransazione is missing in the element Conferma.
        /// </summary>
        internal static string IdTransazioneConferma
        {
            get
            {
                return ResourceManager.GetString("IdTransazioneConferma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The element ConfermaBollettinoPremarcato is missing.
        /// </summary>
        internal static string ConfermaBollettinoPremarcato
        {
            get
            {
                return ResourceManager.GetString("ConfermaBollettinoPremarcato", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The attribute IdUtenza is missing in the element ConfermaBollettinoPremarcato.
        /// </summary>
        internal static string IdUtenzaConfermaBollettinoPremarcato
        {
            get
            {
                return ResourceManager.GetString("IdUtenzaConfermaBollettinoPremarcato", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The attribute CommissioneSuOperazione is missing in the element ConfermaBollettinoPremarcato.
            /// </summary>
            internal static string CommissioneSuOperazioneConfermaBollettinoPremarcato
        {
            get
            {
                return ResourceManager.GetString("CommissioneSuOperazioneConfermaBollettinoPremarcato", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The element ConfermaBollettinoBianco is missing.
        /// </summary>
        internal static string ConfermaBollettinoBianco
        {
            get
            {
                return ResourceManager.GetString("ConfermaBollettinoBianco", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The attribute IdUtenza is missing in the element ConfermaBollettinoBianco.
        /// </summary>
        internal static string IdUtenzaConfermaBollettinoBianco
        {
            get
            {
                return ResourceManager.GetString("IdUtenzaConfermaBollettinoBianco", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The attribute CommissioneSuOperazion is missing in the element ConfermaBollettinoBianco.
        /// </summary>
        internal static string CommissioneSuOperazioneConfermaBollettinoBianco
        {
            get
            {
                return ResourceManager.GetString("CommissioneSuOperazioneConfermaBollettinoBianco", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to The attribute NomeMessaggio is not valid in the element Testata.
        /// </summary>
        internal static string NomeMessaggioTestataNotValid
        {
            get
            {
                return ResourceManager.GetString("NomeMessaggioTestataNotValid", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The element Quietanza is missing.
        /// </summary>
        internal static string Quietanza
        {
            get
            {
                return ResourceManager.GetString("Quietanza", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The attribute CodUffPostaleQuietanza is missing in the element Quietanza.
        /// </summary>
        internal static string CodUffPostaleQuietanza
        {
            get
            {
                return ResourceManager.GetString("CodUffPostaleQuietanza", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The attribute SezUffPostale is missing in the element Quietanza.
        /// </summary>
        internal static string SezUffPostaleQuietanza
        {
            get
            {
                return ResourceManager.GetString("SezUffPostaleQuietanza", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The attribute UffVirtualeQuietanza is missing in the element Quietanza.
        /// </summary>
        internal static string UffVirtualeQuietanza
        {
            get
            {
                return ResourceManager.GetString("UffVirtualeQuietanza", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The attribute CodStruPagQuietanza is missing in the element Quietanza.
        /// </summary>
        internal static string CodStruPagQuietanza
        {
            get
            {
                return ResourceManager.GetString("CodStruPagQuietanza", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The attribute DataAccettazione is missing in the element Quietanza.
        /// </summary>
        internal static string DataAccettazioneQuietanza
        {
            get
            {
                return ResourceManager.GetString("DataAccettazioneQuietanza", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The attribute ProgIncasso is missing in the element Quietanza.
        /// </summary>
        internal static string ProgIncassoQuietanza
        {
            get
            {
                return ResourceManager.GetString("ProgIncassoQuietanza", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The attribute ImportoBollettino is missing in the element Quietanza.
        /// </summary>
        internal static string ImportoBollettinoQuietanza
        {
            get
            {
                return ResourceManager.GetString("ImportoBollettinoQuietanza", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The attribute CommissioniAzienda is missing in the element Quietanza.
        /// </summary>
        internal static string CommissioniAziendaQuietanza
        {
            get
            {
                return ResourceManager.GetString("CommissioniAziendaQuietanza", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The attribute CommissioneAggiuntiva is missing in the element Quietanza.
        /// </summary>
        internal static string CommissioneAggiuntivaQuietanza
        {
            get
            {
                return ResourceManager.GetString("CommissioneAggiuntivaQuietanza", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The attribute NumBollettino is missing in the element Quietanza.
        /// </summary>
        internal static string NumBollettinoQuietanza
        {
            get
            {
                return ResourceManager.GetString("NumBollettinoQuietanza", resourceCulture);
            }
        }            
            

        /// <summary>
        ///   Looks up a localized string similar to The attribute AbiMittente is missing in the element Verifica.
        /// </summary>
        internal static string AbiMittenteQuietanza
        {
            get
            {
                return ResourceManager.GetString("AbiMittenteQuietanza", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The attribute AbiOrdinante is missing in the element Verifica.
        /// </summary>
        internal static string AbiOrdinanteQuietanza
        {
            get
            {
                return ResourceManager.GetString("AbiOrdinanteQuietanza", resourceCulture);
            }
        }
            
        /// <summary>
        ///   Looks up a localized string similar to The element DatiBollettinoPremarcato is missing.
        /// </summary>
        internal static string DatiBollettinoPremarcato
        {
            get
            {
                return ResourceManager.GetString("DatiBollettinoPremarcato", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The attribute NumBollettino is missing in the element DatiBollettinoPremarcato.
        /// </summary>
        internal static string NumBollettinoDatiBollettinoPremarcato
        {
            get
            {
                return ResourceManager.GetString("NumBollettinoDatiBollettinoPremarcato", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The attribute IntConto is missing in the element DatiBollettinoPremarcato.
        /// </summary>
        internal static string IntContoDatiBollettinoPremarcato
        {
            get
            {
                return ResourceManager.GetString("IntContoDatiBollettinoPremarcato", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The attribute IdUtenza is missing in the element DatiBollettinoPremarcato.
        /// </summary>
        internal static string IdUtenzaDatiBollettinoPremarcato
        {
            get
            {
                return ResourceManager.GetString("IdUtenzaDatiBollettinoPremarcato", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The attribute ImportoBollettino is missing in the element DatiBollettinoPremarcato.
        /// </summary>
        internal static string ImportoBollettinoDatiBollettinoPremarcato
        {
            get
            {
                return ResourceManager.GetString("ImportoBollettinoDatiBollettinoPremarcato", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The attribute CommissioneAggiuntiva is missing in the element DatiBollettinoPremarcato.
        /// </summary>
        internal static string CommissioneAggiuntivaDatiBollettinoPremarcato
        {
            get
            {
                return ResourceManager.GetString("CommissioneAggiuntivaDatiBollettinoPremarcato", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The attribute CommissioniAzienda is missing in the element DatiBollettinoPremarcato.
        /// </summary>
        internal static string CommissioniAziendaDatiBollettinoPremarcato
        {
            get
            {
                return ResourceManager.GetString("CommissioniAziendaDatiBollettinoPremarcato", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The attribute CommissioneSuOperazione is missing in the element DatiBollettinoPremarcato.
        /// </summary>
        internal static string CommissioneSuOperazioneDatiBollettinoPremarcato
        {
            get
            {
                return ResourceManager.GetString("CommissioneSuOperazioneDatiBollettinoPremarcato", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The attribute TotaleAddebito is missing in the element DatiBollettinoPremarcato.
        /// </summary>
        internal static string TotaleAddebitoDatiBollettinoPremarcato
        {
            get
            {
                return ResourceManager.GetString("TotaleAddebitoDatiBollettinoPremarcato", resourceCulture);
            }
        } 
            
        /// <summary>
        ///   Looks up a localized string similar to The element DatiBollettinoBianco is missing.
        /// </summary>
        internal static string DatiBollettinoBianco
        {
            get
            {
                return ResourceManager.GetString("DatiBollettinoBianco", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The attribute IntConto is missing in the element DatiBollettinoBianco.
        /// </summary>
        internal static string IntContoDatiBollettinoBianco
        {
            get
            {
                return ResourceManager.GetString("IntContoDatiBollettinoBianco", resourceCulture);
            }
        } 

        /// <summary>
        ///   Looks up a localized string similar to The attribute IdUtenza is missing in the element DatiBollettinoBianco.
        /// </summary>
        internal static string IdUtenzaDatiBollettinoBianco
        {
            get
            {
                return ResourceManager.GetString("IdUtenzaDatiBollettinoBianco", resourceCulture);
            }
        } 

        /// <summary>
        ///   Looks up a localized string similar to The attribute ImportoBollettino is missing in the element DatiBollettinoBianco.
        /// </summary>
        internal static string ImportoBollettinoDatiBollettinoBianco
        {
            get
            {
                return ResourceManager.GetString("ImportoBollettinoDatiBollettinoBianco", resourceCulture);
            }
        } 

        /// <summary>
        ///   Looks up a localized string similar to The attribute CommissioneAggiuntiva is missing in the element DatiBollettinoBianco.
        /// </summary>
        internal static string CommissioneAggiuntivaDatiBollettinoBianco
        {
            get
            {
                return ResourceManager.GetString("CommissioneAggiuntivaDatiBollettinoBianco", resourceCulture);
            }
        } 

        /// <summary>
        ///   Looks up a localized string similar to The attribute CommissioniAzienda is missing in the element DatiBollettinoBianco.
        /// </summary>
        internal static string CommissioniAziendaDatiBollettinoBianco
        {
            get
            {
                return ResourceManager.GetString("CommissioniAziendaDatiBollettinoBianco", resourceCulture);
            }
        } 

        /// <summary>
        ///   Looks up a localized string similar to The attribute CommissioneSuOperazione is missing in the element DatiBollettinoBianco.
        /// </summary>
        internal static string CommissioneSuOperazioneDatiBollettinoBianco
        {
            get
            {
                return ResourceManager.GetString("CommissioneSuOperazioneDatiBollettinoBianco", resourceCulture);
            }
        } 

        /// <summary>
        ///   Looks up a localized string similar to The attribute TotaleAddebito is missing in the element DatiBollettinoBianco.
        /// </summary>
        internal static string TotaleAddebitoDatiBollettinoBianco
        {
            get
            {
                return ResourceManager.GetString("TotaleAddebitoDatiBollettinoBianco", resourceCulture);
            }
        }          

    }
}
